<!DOCTYPE html>
<html>
<head>
    <title>MAGAZINE</title>
</head>
<body>
<h1>MAGAZINE</h1><hr>
<h4>Подробная информация о товаре</h4>
<b>Вид товара: </b>${product.title}<br>
<b>Название товара: </b>${product.name}<br>
<b>Описание товара: </b>${product.description}<br>
<b>Цена: </b>${product.price}<br>
<b>Магазин: </b>${product.magazine}<br>
<hr>
<h1><a href="/">Главная</a></h1><hr>
</body>
</html>